FROM semitechnologies/transformers-inference:custom
# RUN MODEL_NAME=dbmdz/bert-base-turkish-128k-uncased ./download.py
RUN MODEL_NAME=dbmdz/bert-base-turkish-cased ./download.py

# docker build -t m-karakus/systems:bert-base-turkish-cased-v1.0.0 .
# docker push m-karakus/systems:bert-base-turkish-cased-v1.0.0


